# Real-ESRGAN 2x Topaz Finetuning Config
# Usage: python -u realesrgan/train.py -opt options/finetune_topaz_esrgan.yml

name: RealESRGAN_x2_Topaz
model_type: RealESRGANModel
scale: 2
num_gpu: auto
manual_seed: 42

l1_gt_usm: True
percep_gt_usm: True
gan_gt_usm: False
high_order_degradation: false

datasets:
  train:
    name: TopazTrain
    type: RealESRGANPairedDataset
    dataroot_gt: /home/ubuntu/upscaler/datasets/topaz_train/hr_processed
    dataroot_lq: /home/ubuntu/upscaler/datasets/topaz_train/lr_processed
    meta_info: /home/ubuntu/upscaler/datasets/topaz_train/meta_info_train.txt
    io_backend:
      type: disk
    gt_size: 256
    use_hflip: true
    use_rot: true
    use_shuffle: true
    num_worker_per_gpu: 4
    batch_size_per_gpu: 12
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: TopazVal  
    type: PairedImageDataset
    dataroot_gt: /home/ubuntu/upscaler/datasets/topaz_train/hr_processed
    dataroot_lq: /home/ubuntu/upscaler/datasets/topaz_train/lr_processed
    io_backend:
      type: disk

network_g:
  type: RRDBNet
  num_in_ch: 3
  num_out_ch: 3
  num_feat: 64
  num_block: 23
  num_grow_ch: 32
  scale: 2

network_d:
  type: UNetDiscriminatorSN
  num_in_ch: 3
  num_feat: 64
  skip_connection: True

path:
  pretrain_network_g: /home/ubuntu/Real-ESRGAN/experiments/pretrained_models/RealESRGAN_x2plus.pth
  param_key_g: params_ema
  strict_load_g: true
  pretrain_network_d: /home/ubuntu/Real-ESRGAN/experiments/pretrained_models/RealESRGAN_x4plus_netD.pth
  param_key_d: params
  strict_load_d: false
  resume_state: ~

train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]
  optim_d:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [50000, 80000]
    gamma: 0.5

  total_iter: 100000
  warmup_iter: 1000

  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

  perceptual_opt:
    type: PerceptualLoss
    layer_weights:
      'conv1_2': 0.1
      'conv2_2': 0.1
      'conv3_4': 1
      'conv4_4': 1
      'conv5_4': 1
    vgg_type: vgg19
    use_input_norm: true
    perceptual_weight: !!float 1.0
    style_weight: 0
    range_norm: false
    criterion: l1

  gan_opt:
    type: GANLoss
    gan_type: vanilla
    real_label_val: 1.0
    fake_label_val: 0.0
    loss_weight: !!float 1e-1

  net_d_iters: 1
  net_d_init_iters: 0

val:
  val_freq: !!float 5000
  save_img: false
  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 4
      test_y_channel: false
    ssim:
      type: calculate_ssim
      crop_border: 4
      test_y_channel: false

logger:
  print_freq: 100
  save_checkpoint_freq: !!float 10000
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

dist_params:
  backend: nccl
  port: 29500

